package com.arcada.devops;

import java.util.Scanner;
/**
 * Hello world!
 */
public class App {
	
	
    public static void main(String[] args) {
    	
    	
    	Scanner input = new Scanner(System.in);
        System.out.println("Welcome to FriendGallery!");
        
        String nameInput = "";
        
        while (!nameInput.equalsIgnoreCase("Q")) {
	        System.out.println("Please enter a profile name or type \"q\" to quit.");
	        nameInput = input.nextLine();
	        
	        if (nameInput.equalsIgnoreCase("q")) {
	        	break;
	        }
	        
	        String[] friendList = getFriendListOfUser(nameInput);
	        
	        // Output friend list
	        System.out.println("Friend list of user " + nameInput);
	        for (int i = 0; i < friendList.length; i++) {
	        	System.out.println(friendList[i]);
	        }
        }
       
        
    }

	public static String[] getFriendListOfUser(String username) {
    	// Hardcoded friend list (from set of 6 unique full names generated by ChatGPT)
    	String[] sampleFriendList1 = {"David Rodriguez", "Jessica Moore", "Michael Brown"};
    	String[] sampleFriendList2 = {"John Lopez", "Linda Anderson", "Sarah Wilson"};
    	String[] sampleFriendList3 = {"Michael Brown", "Sarah Wilson", "David Rodriguez"};
    	
    	// Sample users (not all names included)
    	User user1 = new User("Linda Anderson", sampleFriendList1);
    	User user2 = new User("Michael Brown", sampleFriendList2);
    	User user3 = new User("Jessica Moore", sampleFriendList3);
    	
    	User[] userDb = {user1, user2, user3};
    	
    	for (int i = 0; i < userDb.length; i++) {
    		if (userDb[i].getUsername().equals(username)) {
    			return userDb[i].getFriendList();
    		}
    		
    	}
    	// Return error array if user not found in database
    	String[] error = {"ERROR: User profile is inaccessible or does not exist."};
    	return error;
    	
    }
}
